version: "3.9"
services:
    mongodb:
        container_name: go_mongodb
        image: mongo
        restart: always
        env_file:
            - ./local.env
        ports:
            - "6000:27017"
        volumes:
            - ./data/mongodb:/data/db

    redis:
        container_name: go_redis
        image: redis:alpine
        ports:
            - "6300:6379"
        volumes:
            - ./data/redis:/data
volumes:
    mongodb:
    redisDB:
